### ISSUE TITLE
Ch 6 - model syncing learning is incomplete

### ISSUE THREAD

**Issue by stewartadam** [charleszipp/abode#22]
The second learning exercise, *Using Time Series Insights with Azure Digital Twin*, links to [this walkthrough](https://docs.microsoft.com/en-us/azure/time-series-insights/tutorials-model-sync) which has incomplete code samples and describes a procedure for instance synchronization, not model/hierarchy synchronization. See also https://github.com/MicrosoftDocs/azure-docs/issues/77641.

In the interim, I think would be worth removing it as at the present time is adds some confusion.

**Comment by charleszipp** [comment]
@jackiebecker since there are issues with the code samples linked in the content, would you be opposed to removing this exercise for the time being? The other article that @stewartadam suggested in #21 will provide a fairly end-to-end exercise.

@stewartadam curious if you have any recommendations for other exercises that you feel would be appropriate with TSI? Perhaps we can replace it with something else that we expect to come up in our engagements.

**Comment by jackiebecker** [comment]
Sure, I'll remove the second exercise. As I stated in the other issue, the tutorial mentioned in #21 was already linked in the content. (See "Integrating ADT with TSI - ~30 min including following steps, assuming prerequisite of ADT instance has been met")

**Comment by charleszipp** [comment]
Resolved with #24
